In [30]:
import pandas as pd

In [31]:
# From Python Lists

In [32]:
data = [['harry' , 34], ["Jill" , 67] , ["Jacob" , 67], ["Shubham" , 90]]

In [33]:
data

[['harry', 34], ['Jill', 67], ['Jacob', 67], ['Shubham', 90]]

In [34]:
pd.DataFrame(data , columns=["Name", "Marks"])

      Name  Marks
0    harry     34
1     Jill     67
2    Jacob     67
3  Shubham     90

In [35]:
# From Dictionary of Lists

In [36]:
data = {"a": [4,5,6], "b":[89,67,43]}

In [37]:
data

{'a': [4, 5, 6], 'b': [89, 67, 43]}

In [38]:
data

{'a': [4, 5, 6], 'b': [89, 67, 43]}

In [39]:
df = pd.DataFrame(data)

In [40]:
df

   a   b
0  4  89
1  5  67
2  6  43

In [41]:
# From NumPy Arrays

In [42]:
import numpy as np

In [43]:
arr = np.array([[1,2],[5,8]])

In [44]:
df = pd.DataFrame(arr, columns=["A","B"])

In [45]:
df

   A  B
0  1  2
1  5  8

In [46]:
pd.read_excel("data.xlsx")

     Name School  Marks
0     ben    rps     45
1     ken    jps     54
2     rev    kps     34
3  harish    lps     45
4    epam   dups     45

In [54]:
df = pd.read_json("data.json")

In [55]:
with open("data.json") as f:
    print(f.read())

{
  "students": [
    {
      "name": "Aarav Sharma",
      "school": "Delhi Public School",
      "marks": 88
    },
    {
      "name": "Riya Verma",
      "school": "St. Mary's School",
      "marks": 92
    },
    {
      "name": "Karan Patel",
      "school": "Greenwood High",
      "marks": 76
    },
    {
      "name": "Ananya Singh",
      "school": "Springdale School",
      "marks": 85
    },
    {
      "name": "Rahul Mehta",
      "school": "Modern School",
      "marks": 90
    }
  ]
}

In [56]:
df = pd.read_json("data.json")

In [57]:
df

                                            students
0  {'name': 'Aarav Sharma', 'school': 'Delhi Publ...
1  {'name': 'Riya Verma', 'school': 'St. Mary's S...
2  {'name': 'Karan Patel', 'school': 'Greenwood H...
3  {'name': 'Ananya Singh', 'school': 'Springdale...
4  {'name': 'Rahul Mehta', 'school': 'Modern Scho...

In [58]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)

In [59]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [60]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [62]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000