In [1]:
import pandas as pd

In [4]:
employees = pd.DataFrame({
    "EmpID" : [1,2,3],
    "Name":["Alice","Bob","Charlie"],
    "DeptID":[10,20,30]
})

In [5]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [6]:
departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [8]:
pd.merge(employees,departments,on="DeptID") #inner join

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [9]:
pd.merge(employees,departments, on="DeptID", how="left") #left join

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [10]:
pd.merge(employees,departments, on="DeptID", how="right") #Right join

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [11]:
pd.merge(employees,departments, on="DeptID", how="outer") #Outer join

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [13]:
df1 = pd.DataFrame({"Name":["Alice","Bob"]})
df2 = pd.DataFrame({"Name":["Charlie","Bob"]})

In [14]:
df1

    Name
0  Alice
1    Bob

In [15]:
df2

      Name
0  Charlie
1      Bob

In [16]:
pd.concat([df1,df2])

      Name
0    Alice
1      Bob
0  Charlie
1      Bob

In [17]:
pd.concat([df1,df2],axis=1)

    Name     Name
0  Alice  Charlie
1    Bob      Bob